[package]
name = "alegen"
version = "0.1.1"
edition = "2021"
license-file="LICENSE"
repository="https://github.com/aleph-lang/alegen"
description="Aleph generator."

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3 

[dependencies]
aleph-syntax-tree = "0.1.1"
